# Generated by Django 4.2.5 on 2023-09-17 02:38

from django.db import migrations, models
import django.db.models.deletion
import storages.backends.s3


class Migration(migrations.Migration):

    dependencies = [
        ('snacksapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnackImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='www.google.com', storage=storages.backends.s3.S3Storage(), upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='snackitem',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='snacksapp.snackimage'),
        ),
    ]
